core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("product.urls")),
    path('admin/', admin.site.urls),
]

product/urls.py
from django.urls import path
from . import views

app_name = "product"

urlpatterns = [
    path("dashboard/", views.DashboardTemplateView.as_view(), name="dashboard"),
    path("auth/login/", views.LoginFormView.as_view(), name="login"),
    path("auth/logout/", views.LogoutTemplateView.as_view(), name="logout"),

    path("product/", views.ProductListView.as_view(), name="product-list"),
    path("product/detail/<int:pk>", views.ProductDetailView.as_view(), name="product-detail"),
    path("product/add/", views.ProductAddView.as_view(), name="product-add"),
    path("product/update/<int:pk>/", views.ProductUpdateView.as_view(), name="product-update"),
    path("product/delete/<int:pk>/", views.ProductDeleteView.as_view(), name="product-delete"),
    #path("barang/cetak_laporan", views.CetakBarangListView.as_view(), name="cetak-barang"),

    # # Url Barang Masuk 
    # path("barang_masuk/", views.barang_masuk, name="barang-masuk"),
    # path("barang_masuk/tambah_barang_masuk/", views.tambah_barang_masuk, name="tambah-barang-masuk"),
    # path("barang_masuk/update_barang_masuk/<int:id>/", views.update_barang_masuk, name="update-barang-masuk"),
    # path("barang_masuk/delete_barang_masuk/<int:id>/", views.delete_barang_masuk, name="delete-barang-masuk"),
    # path("barang_masuk/cetak_laporan", views.CetakBarangMasukListView.as_view(), name="cetak-barang-masuk"),

    # # Url Barang Keluar
    # path("barang_keluar/", views.barang_keluar, name="barang-keluar"),
    # path("barang_keluar/tambah_barang_keluar", views.tambah_barang_keluar, name="tambah-barang-keluar"),
    # path("barang_keluar/update_barang_keluar/<int:id>", views.update_barang_keluar, name="update-barang-keluar"),
    # path("barang_keluar/delete_barang_keluar/<int:id>", views.delete_barang_keluar, name="delete-barang-keluar"),
    # path("barang_keluar/cetak_laporan", views.CetakBarangKeluarListView.as_view(), name="cetak-barang-keluar"),

    
    # path("logout/", views.logout_user, name="logout"),
]

handler404 = "product.views.handling_404"

product/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
 

class Product(models.Model):
    name = models.CharField(max_length=100, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("product:product-detail", kwargs={"pk": self.pk})

product/forms.py
from django import forms
from product.models import Product

class LoginForm(forms.Form):
    username = forms.CharField(label="",
                               max_length=50, 
                               widget=forms.TextInput(
                                   attrs={
                                       "placeholder": "Username",
                                   }
                                   )
                               )
    
    password = forms.CharField(label="",
                               max_length=50,
                               widget=forms.PasswordInput(
                                   attrs={
                                       "placeholder": "password",
                                   }
                               )
                               )

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = (
            "name",
            "category",
            "price"
        )

        wigets = {
            "price": forms.NumberInput(attrs={"min": "0"})
        }

# class FormBarangMasuk(forms.ModelForm):
#     class Meta:
#         model = BarangMasuk
#         fields = (
#             "tanggal_masuk",
#             "barang",
#             "total_barang_masuk",
#         )

#         wigets = {
#             "tanggal_masuk": forms.DateInput(attrs={"type": "date"}),
#             "total_barang_masuk": forms.NumberInput(attrs={"min": "0"}),
#         }

# class FormBarangKeluar(forms.ModelForm):
#     class Meta:
#         model = BarangKeluar
#         fields = (
#             "tanggal_keluar",
#             "barang",
#             "total_barang_keluar",
#         )

#         wigets = {
#             "tanggal_keluar": forms.DateInput(attrs={"type": "date"}),
#             "total_barang_keluar": forms.NumberInput(attrs={"min": "0"}),
#         }


# class FormatForm(forms.Form):
#     class FormatChoices(models.TextChoices):
#         XLSX = "xlsx", "xlsx"
#         CSV = "csv", "csv"
#         JSON = "json", "json"

#     format = forms.ChoiceField(choices=FormatChoices.choices)

product/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from product.models import Product
from product.forms import LoginForm, ProductForm


class DashboardTemplateView(generic.TemplateView):
    template_name = "dashboard.html"

class LoginFormView(generic.FormView):
    template_name = "login.html"
    form_class = LoginForm
    success_url = "/dashboard/"
    
    def post(self, request):
        form = self.get_form()
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, "Login berhasil!")

            return self.form_valid(form)
        
        else:
            return self.form_invalid(form)
        

class LogoutTemplateView(generic.TemplateView):
    template_name = "logout.html"

    def post(self, request):
        logout(request)
        return redirect("product:login")
    

class ProductListView(generic.ListView):
    model = Product
    template_name = "product/product_list.html"
    context_object_name = "products"


class ProductDetailView(generic.DetailView):
    model = Product
    template_name = "product/product_detail.html"


class ProductAddView(generic.CreateView):
    model = Product
    template_name = "product/product_add.html"
    form_class = ProductForm


class ProductUpdateView(generic.UpdateView):
    model = Product
    form_class = ProductForm
    template_name = "product/product_update.html"
    success_url = "/product/"


class ProductDeleteView(generic.DeleteView):
    model = Product
    template_name = "product/product_delete.html"
    success_url = reverse_lazy("product:product-list")

# def is_valid_query(param):
#     return param != "" and param is not None

# def index(request):
#     form = FormLogin()

#     if request.method == "POST":
#         form = FormLogin(request.POST)
#         username = request.POST.get("username")
#         password = request.POST.get("password")
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             login(request, user)
#             messages.success(request, "Berhasil Login !", extra_tags="success")
#             return redirect("dashboard")
#         else:
#             messages.error(request, "Terjadi keslahan, login ulang!")
#             return redirect("index")
        
#     context = {
#             "title": "Index | Django",
#             "form": form,
#         }
#     return render(request, "index.html", context)

# def logout_user(request):
#     logout(request)
#     messages.success(request, "Logout berhasil!")
#     return redirect("index")

# # ===== Area CRUD Barang ===== #

# @login_required(login_url="/")
# def barang(request):
#     data = Barang.objects.all()

#     paginator = Paginator(data, 25)
#     page_number = request.GET.get("page", 1)
#     page_obj = paginator.get_page(page_number)

#     nama_barang = request.GET.get("nama_barang")

#     if is_valid_query(nama_barang):
#         data = data.filter(nama_barang__icontains=nama_barang)

#     context = {
#         "title": "Django | Data Barang",
#         "data": data,
#         "page_obj": page_obj,
#     }
#     return render(request, "barang/barang.html", context)

# @login_required(login_url="/")
# def tambah_barang(request):
#     data = Barang.objects.all()
#     form = FormBarang()

#     if request.method == "POST":
#         form = FormBarang(request.POST)
#         if form.is_valid():
#             form.save()
#             messages.success(request, "Barang berhasil ditambahkan!")
#             return redirect("barang")

#     context = {
#         "title": "Django | Tambah Barang",
#         "data": data,
#         "form": form,
#     }
#     return render(request, "barang/tambah_barang.html", context)

# @login_required(login_url="/")
# def update_barang(request, id):
#     data = Barang.objects.get(id=id)
#     form = FormBarang(instance=data)

#     if request.method == "POST":
#         form = FormBarang(request.POST, instance=data)
#         if form.is_valid():
#             form.save()
            
#             messages.success(request, "Barang berhasil diupdate!")
#             return redirect("barang")
        
#     context = {
#         "title": "Django | Update Barang",
#         "pk": data,
#         "form": form,
#     }
#     return render(request, "barang/update_barang.html", context)

# @login_required(login_url="/")
# def delete_barang(request, id):
#     data = Barang.objects.get(id=id)
#     if request.method == "POST":
#         data.delete()
#         messages.success(request, "Barang berhasil dihapus!")
#         return redirect("barang")

#     context = {
#         "title": "Django | Delete Barang",
#         "data": data,
#     }
#     return render(request, "barang/delete_barang.html", context)


# class CetakBarangListView(ListView, FormView):
#     model = Barang
#     template_name = "barang/cetak_barang.html"
#     form_class = FormatForm

#     def post(self, request, **kwargs):
#         qs = self.get_queryset()
#         dataset = BarangResources().export(qs)
#         format = request.POST.get("format")

#         if format == "xlsx":
#             ds = dataset.xlsx
#         elif format == "csv":
#             ds = dataset.csv
#         else:
#             ds = dataset.json

#         response = HttpResponse(ds, content_type=f"{format}")
#         response["Content-Disposition"] = f"attachment; filename=laporan.{format}"
#         return response

# # ================================== #

# # ===== Area CRUD Barang masuk ===== #

# @login_required(login_url="/")
# def barang_masuk(request):
#     data = BarangMasuk.objects.all()
#     paginator = Paginator(data, 25)
#     page_number = request.GET.get("page", 1)
#     page_obj = paginator.get_page(page_number)

#     tanggal_min = request.GET.get("tanggal_min")
#     tanggal_max = request.GET.get("tanggal_max")

#     if is_valid_query(tanggal_min):
#         data = data.filter(tanggal_masuk__gte=tanggal_min)

#     if is_valid_query(tanggal_max):
#         data = data.filter(tanggal_masuk__lte=tanggal_max)

#     context = {
#         "title": "Django | Data Barang Masuk",
#         "data": data,
#         "page_obj": page_obj,
#     }
#     return render(request, "barang_masuk/barang_masuk.html", context)

# @login_required(login_url="/")
# def tambah_barang_masuk(request):
#     data = BarangMasuk.objects.all()
#     form = FormBarangMasuk()

#     if request.method == "POST":
#         form = FormBarangMasuk(request.POST)
#         if form.is_valid():
#             form.save()
#             messages.success(request, "Barang masuk berhasil ditambahkan!")
#             return redirect("barang-masuk")

#     context = {
#         "title": "Django | Tambah Barang Masuk",
#         "data": data,
#         "form": form,
#     }
#     return render(request, "barang_masuk/tambah_barang_masuk.html", context)

# @login_required(login_url="/")
# def update_barang_masuk(request, id):
#     data = BarangMasuk.objects.get(id=id)
#     form = FormBarangMasuk(instance=data)

#     if request.method == "POST":
#         form = FormBarangMasuk(request.POST, instance=data)
#         if form.is_valid():
#             form.save()
            
#             messages.success(request, "Barang masuk berhasil diupdate!")
#             return redirect("barang-masuk")
        
#     context = {
#         "title": "Django | Update Barang Masuk",
#         "pk": data,
#         "form": form,
#     }
#     return render(request, "barang_masuk/update_barang_masuk.html", context)
        
# @login_required(login_url="/")
# def delete_barang_masuk(request, id):
#     data = BarangMasuk.objects.get(id=id)
#     if request.method == "POST":
#         data.delete()
#         messages.success(request, "Barang masuk berhasil dihapus!")
#         return redirect("barang-masuk")

#     context = {
#         "title": "Django | Delete Barang Masuk",
#         "data": data,
#     }
#     return render(request, "barang_masuk/delete_barang_masuk.html", context)


# class CetakBarangMasukListView(ListView, FormView):
#     model = BarangMasuk
#     template_name = "barang_masuk/cetak_barang_masuk.html"
#     form_class = FormatForm

#     def post(self, request, **kwargs):
#         qs = self.get_queryset()
#         dataset = BarangMasukResources().export(qs)
#         format = request.POST.get("format")

#         if format == "xlsx":
#             ds = dataset.xlsx
#         elif format == "csv":
#             ds = dataset.csv
#         else:
#             ds = dataset.json

#         response = HttpResponse(ds, content_type=f"{format}")
#         response["Content-Disposition"] = f"attachment; filename=laporan.{format}"
#         return response
# # =========================================================================================== #

# # ===== Area CRUD Barang keluar ===== #

# @login_required(login_url="/")
# def barang_keluar(request):
#     data = BarangKeluar.objects.all()
#     paginator = Paginator(data, 25)
#     page_number = request.GET.get("page", 1)
#     page_obj = paginator.get_page(page_number)

#     tanggal_min = request.GET.get("tanggal_min")
#     tanggal_max = request.GET.get("tanggal_max")

#     if is_valid_query(tanggal_min):
#         data = data.filter(tanggal_keluar__gte=tanggal_min)

#     if is_valid_query(tanggal_max):
#         data = data.filter(tanggal_keluar__lte=tanggal_max)

#     context = {
#         "title": "Django | Data Barang Keluar",
#         "data": data,
#         "page_obj": page_obj,
#     }

product/templates/product/cetak_barang.html
{% extends "layout/base.html"%}

{% block title %}{{ title }}{% endblock %}

{% block content %}
{% include "layout/alert.html"%}

<div class="container">
</div>

<div class="container mt-4 p-4">
    <div class="d-flex justify-content-center align-items-center">
        <div>
            <h1 class="text-center">Cetak Barang</h1> <hr> <br>
            <a href="" data-bs-toggle="modal" data-bs-target="#cetakModal" class="btn btn-success px-5 btn-sm">Cetak Laporan</a>
            <a href="{% url 'barang' %}" class="btn btn-secondary px-5 btn-sm">Kembali</a>
        </div>
    </div>
  <br />

  <!-- Modal Tambah -->
  <div class="modal fade" id="cetakModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="cetakModal" aria-hidden="true">
    <div class="modal-dialog">
      <form action="" method="POST">
        {% csrf_token %}
        <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="cetakModal">Cetak Data Barang</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Kembali</button>
              <button type="submit" class="btn btn-success">Cetak</button>
            </div>
          </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

product/templates/product/product_add.html
{% extends "layout/base.html" %}

{% block title%}Tambah Barang{% endblock %}

{% block content %}

<div class="container">
    <form method="POST">
        {% csrf_token %}
        <div class="d-flex justify-content-center align-items-center">
            <div>
                <h1>Add Product</h1> <hr> <br>
                <table>
                    {{ form.as_table }}
                </table>
                <div> <br>
                    <input type="submit" class="btn btn-sm btn-success" value="Tambah">
                    <a class="btn btn-sm btn-secondary" type="button" href="{% url 'product:product-list' %}">Kembali</a>
                </div>
            </div>
            
        </div>
    </form>    
</div>

{% endblock %}

product/templates/product/product_delete.html
{% extends "layout/base.html" %}

{% block title%}{{title}}{% endblock %}

{% block content %}
{% include "layout/alert.html"%}

<div class="container">
    <form method="POST">
        {% csrf_token %}
        <div class="d-flex justify-content-center align-items-center"> 
            <div>
                <h1>Delete Product</h1> <hr> <br>
                <p>Anda yakin ingin menghapus data berikut? </p>
                <table class="text-center table table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Category</th>
                            <th>Price</th>
                            <th>Quantity</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ object.id }}</td>
                            <td>{{ object.name }}</td>
                            <td>{{ object.category }}</td>
                            <td>{{ object.price }}</td>
                            <td>{{ object.quantity }}</td>
                        </tr>
                    </tbody>
                </table>
                <div>
                    <input type="submit" class="btn btn-sm btn-danger" value="Delete">
                    <a class="btn btn-sm btn-secondary" type="button" href="{{ object.get_absolute_url }}">Kembali</a>
                </div>
            </div>
        </div>
        
    </form>    
</div>

{% endblock %}

product/templates/product/product_detail.html
{% extends "layout/base.html" %}

{% block title%}{% endblock %}

{% block content %}
{% include "layout/alert.html"%}


<div class="container">
    <h1>{{ object.name }}</h1>

    <a href="{% url 'product:product-update' object.id %}" class="btn btn-warning btn-sm">Update</a>
    <a href="{% url 'product:product-delete' object.id %}" class="btn btn-danger btn-sm">Delete</a>
</div>

{% endblock %}

product/templates/product/product_list.html
{% extends "layout/base.html"%}

{% block title %}{{ title }}{% endblock %}

{% block content %}
{% include "layout/navbar.html"%}

<div class="container">
    <h1>List Product</h1> 
</div>

<!-- <div class="container mt-5 p-3 border rounded">
    <div class="d-flex align-items-center">
        <div>
            <h4>Filter Barang</h4> <br>
            <form action="" method="GET" class="d-flex">
                <input type="text" name="nama_barang" value="" class="form-control" placeholder="Cari Nama Barang"/>
                <button class="btn btn-sm btn-success mx-2" name="search">Search</button>
            </form>
        </div>
    </div>
</div> -->

<div class="container mt-4 p-5 border rounded">
    <div class="d-flex justify-content-between align-items-center">
        <div>
            <a href="{% url 'product:product-add' %}" class="btn btn-primary px-5 btn-sm">Add</a>
        </div>
    </div>
    <br/>
        <table class=" text-center table table-bordered">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Quantity</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr>
                    <td><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></td>
                    <td>{{ product.quantity }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div> 

{% endblock %}

product/templates/product/product_update.html
{% extends "layout/base.html" %}

{% block title%}{{title}}{% endblock %}

{% block content %}
{% include "layout/alert.html"%}


<div class="container">
    <form method="POST">
        {% csrf_token %}
        <div class="d-flex justify-content-center align-items-center">
            <div>
                <h1>Update Product</h1> <hr> <br>
                <table>
                    {{ form.as_table }}
                </table>
                <div> <br>
                    <input type="submit" class="btn btn-sm btn-warning" value="Update">
                    <a class="btn btn-sm btn-secondary" type="button" href="{{ object.get_absolute_url }}">Kembali</a>
                </div>
            </div>
        </div>
        
    </form>    
</div>

{% endblock %}